language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "AFl6ZHTD8iaAe1ZpkFuZHwAOItJyo3GoCZy5OFypYrPGP+hoTtcWPwkscx+D+3RPmBJBh4I8qOaQfUIPpVpqXXXhbEUyFt2ZSb34IxBbPxLJIPesjQ1DAWaDOGs0Rfv9vDD/nVXbXv1mkRunDkDowK82eUR8EQlu4VTotIb4AZ/kAzxlXl2GSYoSVJBKx8I5TMWMwNZOiojVg3PP9fAwB+9SwYgjFZ6xHoBJLi/ym7gnpG734Vn0aVgTrcTo9EKm5TxbiuDYnqfgjoRQyaXf4ne26zitkS3ULnKLIQgS5eSQjiQm9r9AL8SXdhuP2ckJhz78tl5K20D/CoryvhbnIm/CVsfseQN/EWOElBUPN6/bSNCfWS9itVLnNts94NYyW4gvRADSr3BfQjYWF3RJ1MfgsR9gBR6+o8nPaGqPB3pAnrYtyB++dw+4f4PU98Z1cMzku1JGVZRDgCd9rPSg2+x0wZX9yEs/TNUbc9B8JDYh8dMVhTWQ7rLlOHF94rz21KfZ300tSVzl8306vnvWbx/iyUdel6VtVQ1I2LTcc5pNUViC/v07hcMYTg93SBXD18M3rJaLkoB5Y/TSx2MmN3V5PkzdLdx8mb0kF4K1uQixkZ1FGwxFnKUbmp6yPoGXy93wdH/yPlXf7UiNcMvr7ZnZgAPDKrhI25Ah/8qMF3U="
    on:
      tags: true
      all_branches: true
